#############################################################################
# Makefile for building: bin/app
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  app.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile app.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = app1.0.0
DISTDIR = /home/mkopyt/QT-SuperMemo/build/app1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/ActivityStatisticsWindow.cc \
		src/Card.cc \
		src/ChangeUserWindow.cc \
		src/Course.cc \
		src/CoursesManager.cc \
		src/LearningWindow.cc \
		src/MainMenuWindow.cc \
		src/NewQuestion.cc \
		src/Settings.cc \
		src/SettingsWindow.cc \
		src/TypesOfAnswerStatisticsWindow.cc \
		src/User.cc \
		src/UserCalendarWindow.cc \
		src/UserStats.cc \
		src/main.cc build/qrc_resources.cpp \
		build/moc_ActivityStatisticsWindow.cpp \
		build/moc_ChangeUserWindow.cpp \
		build/moc_LearningWindow.cpp \
		build/moc_MainMenuWindow.cpp \
		build/moc_NewQuestion.cpp \
		build/moc_SettingsWindow.cpp \
		build/moc_TypesOfAnswerStatisticsWindow.cpp \
		build/moc_UserCalendarWindow.cpp
OBJECTS       = build/ActivityStatisticsWindow.o \
		build/Card.o \
		build/ChangeUserWindow.o \
		build/Course.o \
		build/CoursesManager.o \
		build/LearningWindow.o \
		build/MainMenuWindow.o \
		build/NewQuestion.o \
		build/Settings.o \
		build/SettingsWindow.o \
		build/TypesOfAnswerStatisticsWindow.o \
		build/User.o \
		build/UserCalendarWindow.o \
		build/UserStats.o \
		build/main.o \
		build/qrc_resources.o \
		build/moc_ActivityStatisticsWindow.o \
		build/moc_ChangeUserWindow.o \
		build/moc_LearningWindow.o \
		build/moc_MainMenuWindow.o \
		build/moc_NewQuestion.o \
		build/moc_SettingsWindow.o \
		build/moc_TypesOfAnswerStatisticsWindow.o \
		build/moc_UserCalendarWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		app.pro include/ActivityStatisticsWindow.h \
		include/AnswerType.h \
		include/Card.h \
		include/ChangeUserWindow.h \
		include/Course.h \
		include/CoursesManager.h \
		include/LearningWindow.h \
		include/MainMenuWindow.h \
		include/NewQuestion.h \
		include/Settings.h \
		include/SettingsWindow.h \
		include/TypesOfAnswerStatisticsWindow.h \
		include/User.h \
		include/UserCalendarWindow.h \
		include/UserStats.h src/ActivityStatisticsWindow.cc \
		src/Card.cc \
		src/ChangeUserWindow.cc \
		src/Course.cc \
		src/CoursesManager.cc \
		src/LearningWindow.cc \
		src/MainMenuWindow.cc \
		src/NewQuestion.cc \
		src/Settings.cc \
		src/SettingsWindow.cc \
		src/TypesOfAnswerStatisticsWindow.cc \
		src/User.cc \
		src/UserCalendarWindow.cc \
		src/UserStats.cc \
		src/main.cc
QMAKE_TARGET  = app
DESTDIR       = bin/
TARGET        = bin/app


first: all
####### Build rules

bin/app: build/ui_ActivityStatisticsWindow.h build/ui_ChangeUserWindow.h build/ui_LearningWindow.h build/ui_MainMenuWindow.h build/ui_NewQuestion.h build/ui_SettingsWindow.h build/ui_TypesOfAnswerStatisticsWindow.h build/ui_UserCalendarWindow.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: app.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		app.pro \
		resources/resources.qrc
	$(QMAKE) -o Makefile app.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
app.pro:
resources/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile app.pro

qmake_all: FORCE


all: Makefile bin/app

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/ActivityStatisticsWindow.h include/AnswerType.h include/Card.h include/ChangeUserWindow.h include/Course.h include/CoursesManager.h include/LearningWindow.h include/MainMenuWindow.h include/NewQuestion.h include/Settings.h include/SettingsWindow.h include/TypesOfAnswerStatisticsWindow.h include/User.h include/UserCalendarWindow.h include/UserStats.h $(DISTDIR)/
	$(COPY_FILE) --parents src/ActivityStatisticsWindow.cc src/Card.cc src/ChangeUserWindow.cc src/Course.cc src/CoursesManager.cc src/LearningWindow.cc src/MainMenuWindow.cc src/NewQuestion.cc src/Settings.cc src/SettingsWindow.cc src/TypesOfAnswerStatisticsWindow.cc src/User.cc src/UserCalendarWindow.cc src/UserStats.cc src/main.cc $(DISTDIR)/
	$(COPY_FILE) --parents forms/ActivityStatisticsWindow.ui forms/ChangeUserWindow.ui forms/LearningWindow.ui forms/MainMenuWindow.ui forms/NewQuestion.ui forms/SettingsWindow.ui forms/TypesOfAnswerStatisticsWindow.ui forms/UserCalendarWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

test:
	cd tests && qmake && make && ./tests

extraclean:
	rm -f -r build/* bin/* && rm -f .qmake.stash tests/.qmake.stash tests/tests tests/Makefile

clean: extraclean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_resources.cpp
build/qrc_resources.cpp: resources/resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/default_image.jpg \
		resources/congratulations.png \
		resources/Icons/smile.png \
		resources/Icons/sound.png \
		resources/Icons/Supermemo-icon.png \
		resources/Icons/neutral.png \
		resources/Icons/photo.png \
		resources/Icons/sad.png
	/usr/lib/qt5/bin/rcc -name resources resources/resources.qrc -o build/qrc_resources.cpp

compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o build/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_ActivityStatisticsWindow.cpp build/moc_ChangeUserWindow.cpp build/moc_LearningWindow.cpp build/moc_MainMenuWindow.cpp build/moc_NewQuestion.cpp build/moc_SettingsWindow.cpp build/moc_TypesOfAnswerStatisticsWindow.cpp build/moc_UserCalendarWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_ActivityStatisticsWindow.cpp build/moc_ChangeUserWindow.cpp build/moc_LearningWindow.cpp build/moc_MainMenuWindow.cpp build/moc_NewQuestion.cpp build/moc_SettingsWindow.cpp build/moc_TypesOfAnswerStatisticsWindow.cpp build/moc_UserCalendarWindow.cpp
build/moc_ActivityStatisticsWindow.cpp: include/ActivityStatisticsWindow.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/ActivityStatisticsWindow.h -o build/moc_ActivityStatisticsWindow.cpp

build/moc_ChangeUserWindow.cpp: include/ChangeUserWindow.h \
		include/User.h \
		include/Course.h \
		include/Card.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/ChangeUserWindow.h -o build/moc_ChangeUserWindow.cpp

build/moc_LearningWindow.cpp: include/LearningWindow.h \
		include/NewQuestion.h \
		include/Card.h \
		include/Course.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/LearningWindow.h -o build/moc_LearningWindow.cpp

build/moc_MainMenuWindow.cpp: include/MainMenuWindow.h \
		include/Card.h \
		include/Course.h \
		include/LearningWindow.h \
		include/NewQuestion.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		include/User.h \
		include/ChangeUserWindow.h \
		include/SettingsWindow.h \
		include/Settings.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/MainMenuWindow.h -o build/moc_MainMenuWindow.cpp

build/moc_NewQuestion.cpp: include/NewQuestion.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/NewQuestion.h -o build/moc_NewQuestion.cpp

build/moc_SettingsWindow.cpp: include/SettingsWindow.h \
		include/Settings.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/SettingsWindow.h -o build/moc_SettingsWindow.cpp

build/moc_TypesOfAnswerStatisticsWindow.cpp: include/TypesOfAnswerStatisticsWindow.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/TypesOfAnswerStatisticsWindow.h -o build/moc_TypesOfAnswerStatisticsWindow.cpp

build/moc_UserCalendarWindow.cpp: include/UserCalendarWindow.h \
		include/CoursesManager.h \
		include/Course.h \
		include/Card.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mkopyt/QT-SuperMemo/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mkopyt/QT-SuperMemo -I/home/mkopyt/QT-SuperMemo/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/UserCalendarWindow.h -o build/moc_UserCalendarWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_ActivityStatisticsWindow.h build/ui_ChangeUserWindow.h build/ui_LearningWindow.h build/ui_MainMenuWindow.h build/ui_NewQuestion.h build/ui_SettingsWindow.h build/ui_TypesOfAnswerStatisticsWindow.h build/ui_UserCalendarWindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_ActivityStatisticsWindow.h build/ui_ChangeUserWindow.h build/ui_LearningWindow.h build/ui_MainMenuWindow.h build/ui_NewQuestion.h build/ui_SettingsWindow.h build/ui_TypesOfAnswerStatisticsWindow.h build/ui_UserCalendarWindow.h
build/ui_ActivityStatisticsWindow.h: forms/ActivityStatisticsWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/ActivityStatisticsWindow.ui -o build/ui_ActivityStatisticsWindow.h

build/ui_ChangeUserWindow.h: forms/ChangeUserWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/ChangeUserWindow.ui -o build/ui_ChangeUserWindow.h

build/ui_LearningWindow.h: forms/LearningWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/LearningWindow.ui -o build/ui_LearningWindow.h

build/ui_MainMenuWindow.h: forms/MainMenuWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/MainMenuWindow.ui -o build/ui_MainMenuWindow.h

build/ui_NewQuestion.h: forms/NewQuestion.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/NewQuestion.ui -o build/ui_NewQuestion.h

build/ui_SettingsWindow.h: forms/SettingsWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/SettingsWindow.ui -o build/ui_SettingsWindow.h

build/ui_TypesOfAnswerStatisticsWindow.h: forms/TypesOfAnswerStatisticsWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/TypesOfAnswerStatisticsWindow.ui -o build/ui_TypesOfAnswerStatisticsWindow.h

build/ui_UserCalendarWindow.h: forms/UserCalendarWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/UserCalendarWindow.ui -o build/ui_UserCalendarWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/ActivityStatisticsWindow.o: src/ActivityStatisticsWindow.cc include/ActivityStatisticsWindow.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/ui_ActivityStatisticsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ActivityStatisticsWindow.o src/ActivityStatisticsWindow.cc

build/Card.o: src/Card.cc include/Card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Card.o src/Card.cc

build/ChangeUserWindow.o: src/ChangeUserWindow.cc include/ChangeUserWindow.h \
		include/User.h \
		include/Course.h \
		include/Card.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/ui_ChangeUserWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ChangeUserWindow.o src/ChangeUserWindow.cc

build/Course.o: src/Course.cc include/Course.h \
		include/Card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Course.o src/Course.cc

build/CoursesManager.o: src/CoursesManager.cc include/CoursesManager.h \
		include/Course.h \
		include/Card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/CoursesManager.o src/CoursesManager.cc

build/LearningWindow.o: src/LearningWindow.cc include/LearningWindow.h \
		include/NewQuestion.h \
		include/Card.h \
		include/Course.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/ui_LearningWindow.h \
		include/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/LearningWindow.o src/LearningWindow.cc

build/MainMenuWindow.o: src/MainMenuWindow.cc include/MainMenuWindow.h \
		include/Card.h \
		include/Course.h \
		include/LearningWindow.h \
		include/NewQuestion.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		include/User.h \
		include/ChangeUserWindow.h \
		include/SettingsWindow.h \
		include/Settings.h \
		build/ui_MainMenuWindow.h \
		include/UserCalendarWindow.h \
		include/TypesOfAnswerStatisticsWindow.h \
		include/ActivityStatisticsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainMenuWindow.o src/MainMenuWindow.cc

build/NewQuestion.o: src/NewQuestion.cc include/NewQuestion.h \
		build/ui_NewQuestion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/NewQuestion.o src/NewQuestion.cc

build/Settings.o: src/Settings.cc include/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Settings.o src/Settings.cc

build/SettingsWindow.o: src/SettingsWindow.cc include/SettingsWindow.h \
		include/Settings.h \
		build/ui_SettingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SettingsWindow.o src/SettingsWindow.cc

build/TypesOfAnswerStatisticsWindow.o: src/TypesOfAnswerStatisticsWindow.cc include/TypesOfAnswerStatisticsWindow.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/ui_TypesOfAnswerStatisticsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TypesOfAnswerStatisticsWindow.o src/TypesOfAnswerStatisticsWindow.cc

build/User.o: src/User.cc include/User.h \
		include/Course.h \
		include/Card.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/User.o src/User.cc

build/UserCalendarWindow.o: src/UserCalendarWindow.cc include/UserCalendarWindow.h \
		include/CoursesManager.h \
		include/Course.h \
		include/Card.h \
		include/UserStats.h \
		include/AnswerType.h \
		build/ui_UserCalendarWindow.h \
		include/LearningWindow.h \
		include/NewQuestion.h \
		include/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/UserCalendarWindow.o src/UserCalendarWindow.cc

build/UserStats.o: src/UserStats.cc include/UserStats.h \
		include/AnswerType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/UserStats.o src/UserStats.cc

build/main.o: src/main.cc include/MainMenuWindow.h \
		include/Card.h \
		include/Course.h \
		include/LearningWindow.h \
		include/NewQuestion.h \
		include/CoursesManager.h \
		include/UserStats.h \
		include/AnswerType.h \
		include/User.h \
		include/ChangeUserWindow.h \
		include/SettingsWindow.h \
		include/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cc

build/qrc_resources.o: build/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_resources.o build/qrc_resources.cpp

build/moc_ActivityStatisticsWindow.o: build/moc_ActivityStatisticsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ActivityStatisticsWindow.o build/moc_ActivityStatisticsWindow.cpp

build/moc_ChangeUserWindow.o: build/moc_ChangeUserWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ChangeUserWindow.o build/moc_ChangeUserWindow.cpp

build/moc_LearningWindow.o: build/moc_LearningWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_LearningWindow.o build/moc_LearningWindow.cpp

build/moc_MainMenuWindow.o: build/moc_MainMenuWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainMenuWindow.o build/moc_MainMenuWindow.cpp

build/moc_NewQuestion.o: build/moc_NewQuestion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_NewQuestion.o build/moc_NewQuestion.cpp

build/moc_SettingsWindow.o: build/moc_SettingsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_SettingsWindow.o build/moc_SettingsWindow.cpp

build/moc_TypesOfAnswerStatisticsWindow.o: build/moc_TypesOfAnswerStatisticsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_TypesOfAnswerStatisticsWindow.o build/moc_TypesOfAnswerStatisticsWindow.cpp

build/moc_UserCalendarWindow.o: build/moc_UserCalendarWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_UserCalendarWindow.o build/moc_UserCalendarWindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/app/bin || mkdir -p $(INSTALL_ROOT)/opt/app/bin
	-$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/opt/app/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/app/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/app/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/app/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

